#!/usr/bin/env bash
#

# 全局变量定义
aladdin_company="baidu"
aladdin_author="leunggeorge"
date_time=`date +%Y-%m-%d\ %H:%M:%S`

##################################################################
# 代码由此开始 

# 红色打印
echo_red()
{
    while [ "$1" != "" ];do
        echo -e "\033[31;1m$1\033[0m"
        shift
    done
}

# 绿色打印
echo_green()
{
    while [ "$1" != "" ];do
        echo -e "\033[32;1m$1\033[0m"
        shift
    done
}

# 粉色打印
echo_purple()
{
    echo -e "\033[35;1m$1\033[0m"
}


# yes or no print
echo_ok()
{
    if [ $1 -eq 0 ];then
        echo -e "\033[32;1m$2\033[0m"
    else
        echo -e "\033[31;1m$3\033[0m"
    fi
}

# 打印用法
usage()
{
    aladdin_begin
    echo_green "# 自动化更新工具 #"
    cat << END
接口人: $aladdin_author (有问题找ta)
  用法:
        <普通命令 for common>
        aladdin [help]                       打印我
        aladdin pullmaster                   切换到master分支并更新
        aladdin pullcur                      更新当前分支
        aladdin push                         push当前分支
        aladdin preview [blog|doraemon]      预览当前目录的blog（hexo blog；doraemon周刊）
        aladdin publish [blog|doraemon]      发布当前目录的blog（hexo blog；doraemon周刊）
        aladdin status                       更新当前分支状态
        aladdin deploy [dev]                 部署当前分支到otp机器（具体查看模块fis配置）
END
}

# aladdin 开始
aladdin_begin(){
    echo_green "|   ^ ^                   Hi, $USER                    "
    echo_green "|    o    .:[I]:_       Welcome use aladdin     ,:[I]:."
    echo_green "|       .: :[C]: :-.     _= made by lyz =_   ,-: :[C]: :."
    echo_green "|     .: : :[O]: : :\`._                  ,.\': : :[O]: : :."
    echo_green "| _..: : : :[D]: : : : : :-._________.-: : : : : :[D]: : : :-._"
    echo_green "| ^^^^^^^^^^[E]^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^[E]^^^^^^^^^^"
    echo_green "|           [|]                                   [|]"
    echo_green "|   ~~^-_~^~|||~~^_~^~_~^-~_^~-^~_^~~-^~_~^~-^~_^~|||~^-~_~^--"
    echo_green "|"
    b=""
    for i in `seq 0 5 100`
    do
        b=">$b"
        if [ "$(uname)"=="Darwin" ]; then
            # Do something under Mac OS X platform   
            printf "progress:[%+50s]%d%%\r" $b $i
        elif [ "$(expr substr $(uname -s) 1 5)"=="Linux" ]; then
            # Do something under GNU/Linux platform
            printf "progress:[%-50s]%d%%\r" $b $i
        else
            # Do something under other platform
            printf "progress:[%-50s]%d%%\r" $b $i
        fi
        #sleep 0.05
    done
    printf "\n"
    #echo_green ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
}

# aladdin 结束
aladdin_end(){
    echo_green ""
}

# aladdin 本地目录代码更新
aladdin_pullmaster(){
    for dir in $(ls $(pwd));do
        if [ -d $dir ];then
            aladdin_begin

            echo_green $(pwd)/$dir
            cd $dir
            git checkout master
            git pull
            git status
            echo_ok 0 "update success!"
            cd ../
            echo_green $(pwd)
            aladdin_end
        fi
    done
}

# aladdin 本地目录代码更新
aladdin_pullcur(){
    for dir in $(ls $(pwd));do
        if [ -d $dir ];then
            aladdin_begin

            echo_green $(pwd)/$dir
            cd $dir
            git pull
            git status
            echo_ok 0 "update success!"
            cd ../
            echo_green $(pwd)
            aladdin_end
        fi
    done
}

# aladdin 本目录代码提交，默认comment
aladdin_push(){
    aladdin_begin

    echo_green $(pwd)
    git pull
    git add .
    git commit -m "auto commit by robot"
    git push
    git pull
    git status
    echo_ok 0 "update success!"

    aladdin_end
}

aladdin_deploy(){
    echo_red $2
    for dir in $(ls $(pwd));do
        if [ -d $dir ];then
            echo_green $(pwd)/$dir
            cd $dir

            if [ -f "fis-conf.js" ];then
                aladdin_begin

                fis3 release $2
                echo_ok 0 "update success!"
                echo_green $(pwd)
                aladdin_end
            else
                echo_red "no fis conf file."
            fi

            cd ../
        fi
    done

    if [ -f "fis-conf.js" ];then
        aladdin_begin

        curDir=`pwd`
        echo_green "$curDir"
        fis3 release $2 -w
        echo_ok 0 "update success!"
        echo_green $(pwd)

        aladdin_end
    else
        echo_red "no fis conf file."
    fi
}

aladdin_status(){
    for dir in $(ls $(pwd));do
        if [ -d $dir ];then
            aladdin_begin

            echo_green $(pwd)/$dir
            cd $dir
            git status
            cd ../

            aladdin_end
        fi
    done
}

aladdin_preview(){
    aladdin_begin
    echo_red $2

    if [ "$2" = "blog" ];then
        hexo g
        hexo s --debug
    elif [ "$2" = "doraemon" ];then
        rake serve
    fi

    aladdin_end
}

aladdin_publish(){
    aladdin_begin
    echo_red $2

    if [ "$2" = "blog" ];then
        git pull

        hexo clean
        hexo g
        hexo d

        cp baidu-verify-F90255460A.txt ./public/
        git add --all
        git commit -m "auto commit"
        git push origin hexo
    elif [ "$2" = "doraemon" ];then
        git pull
        git add .
        git commit -m "auto commit by robot"
        git push
        git pull
        git status
    fi

    aladdin_end
}

##################################################################
# 一切从这里开始
# -1. logo
echo_green "=== aladdin(@$aladdin_company,by $aladdin_author) $* ==="
# 1. lets go
case C$1 in
    Cdeploy)
        aladdin_deploy $1 $2
        ;;
    Cpullmaster)
        aladdin_pullmaster
        ;;
    Cpush)
        aladdin_push
        ;;
    Cpullcur)
        aladdin_pullcur
        ;;
    Cstatus)
        aladdin_status
        ;;
    Cpreview)
        aladdin_preview $1 $2
        ;;
    Cpublish)
        aladdin_publish $1 $2
        ;;
    C|Chelp)
        usage
        ;;
esac

echo_green "update time = $date_time"
#echo ""
