#!/bin/bash
#
aladdin_company="baidu"
aladdin_author="liangyuanzheng"
date_time=`date +%Y-%m-%d\ %H:%M:%S`

##################################################################
# 代码由此开始 

# 打印用法
usage()
{
    aladdin_begin
    echo_green "# 自动化更新工具 #"
    cat << END
接口人: $aladdin_author (有问题找ta)
  用法:
        <普通命令 for common>
        aladdin [help]                       打印我
        aladdin pullmaster                   切换到master分支并更新
        aladdin pullcur                      更新当前分支
        aladdin status                       更新当前分支状态
        aladdin deploy                       部署当前分支到otp机器（具体查看模块fis配置）
END
}

# yes or no print
echo_ok()
{
    if [ $1 -eq 0 ];then
        echo -e "\033[32;1m$2\033[0m"
    else
        echo -e "\033[31;1m$3\033[0m"
        exit 1
    fi
}
# 红色打印
echo_red()
{
    while [ "$1" != "" ];do
        echo -e "\033[31;1m$1\033[0m"
        shift
    done
}
# 绿色打印
echo_green()
{
    while [ "$1" != "" ];do
        echo -e "\033[32;1m$1\033[0m"
        shift
    done
}
# 粉色打印
echo_purple()
{
    echo -e "\033[35;1m$1\033[0m"
}

# aladdin 开始
aladdin_begin(){
    echo_green "    ^ ^      |              Hi, friend             |"
    echo_green "|    o    .:[I]:_       Welcome use aladdin     ,:[I]:."
    echo_green "|       .: :[C]: :-.     _= made by lyz =_   ,-: :[C]: :."
    echo_green "|     .: : :[O]: : :\`._                  ,.\': : :[O]: : :."
    echo_green "| _..: : : :[D]: : : : : :-._________.-: : : : : :[D]: : : :-._"
    echo_green "| ^^^^^^^^^^[E]^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^[E]^^^^^^^^^^"
    echo_green "|           [|]                                   [|]"
    echo_green "|   ~~^-_~^~|||~~^_~^~_~^-~_^~-^~_^~~-^~_~^~-^~_^~|||~^-~_~^--"
    echo_green "|"
    b=""
    for i in `seq 0 5 100`
    do
        b=">$b"
        printf "progress:[%+50s]%d%%\r" $b $i
        sleep 0.05
    done
    printf "\n"
    #echo_green ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
}

# aladdin 结束
aladdin_end(){
    echo_green ""
}

# aladdin 本地目录代码更新
aladdin_pullmaster(){
    for dir in $(ls $(pwd));do
        if [ -d $dir ];then
            aladdin_begin

            echo_green $(pwd)/$dir
            cd $dir
            git checkout master
            git pull
            git status
            echo_ok 0 "update success!"
            cd ../
            echo_green $(pwd)
            aladdin_end
        fi
    done
}

# aladdin 本地目录代码更新
aladdin_pullcur(){
    for dir in $(ls $(pwd));do
        if [ -d $dir ];then
            aladdin_begin

            echo_green $(pwd)/$dir
            cd $dir
            git status
            git pull
            git status
            echo_ok 0 "update success!"
            cd ../
            echo_green $(pwd)
            aladdin_end
        fi
    done
}

# aladdin 本目录代码提交，默认comment
aladdin_push(){
    aladdin_begin

    echo_green $(pwd)
    git pull
    git add .
    git commit -m "auto added by robot"
    git push
    git status
    echo_ok 0 "update success!"

    aladdin_end
}

aladdin_deploy(){
    echo_red $2
    for dir in $(ls $(pwd));do
        if [ -d $dir ];then
            aladdin_begin

            echo_green $(pwd)/$dir
            cd $dir
            fis3 release $2
            echo_ok 0 "update success!"
            cd ../
            echo_green $(pwd)
            aladdin_end
        fi
    done
}

aladdin_status(){
    for dir in $(ls $(pwd));do
        if [ -d $dir ];then
            aladdin_begin

            echo_green $(pwd)/$dir
            cd $dir
            git status
            cd ../

            aladdin_end
        fi
    done
}

##################################################################
# 一切从这里开始
# -1. logo
echo_green "=== aladdin(@$aladdin_company,by $aladdin_author) $* ==="
# 1. lets go
case C$1 in
    Cdeploy)
        aladdin_deploy $1 $2
        ;;
    Cpullmaster)
        aladdin_pullmaster
        ;;
    Cpush)
        aladdin_push
        ;;
    Cpullcur)
        aladdin_pullcur
        ;;
    Cstatus)
        aladdin_status
        ;;
    C|Chelp)
        usage
        ;;
esac

echo_green "update time = $date_time"
#echo ""
