#!/bin/bash
#
#
#
# setp 1. add script to ~/.zshrc or ~/.bashrc
# step 2. on the basis of your *rc file, exec  source ~/.zshrc or  source ~/.bashrc
#
#if [ -f /home/work/github/aladdin/my_alias ]; then
#    . /home/work/github/aladdin/my_alias
#fi

alias rm='rm -i'
alias aladdin="/bin/zsh /home/work/github/aladdin/aladdin"
alias work="cd /home/work/; ll; echo 'current path is:'; pwd;"
alias godb_self="mysql -h127.0.0.1 -uroot -p"
alias blog="cd /home/work/github/blog; ll; echo 'current path is:'; pwd;"

#==================
# cd alias
#==================
# {{
# Easier navigation: .., ..., ...., ....., ~ and -
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ~="cd ~" # `cd` is probably faster to type though

alias cd-="cd -"
alias cd..="cd .."
alias cd...="cd ../.."
# }} cd

#==================
# ls alias
#==================
# {{
# Detect which `ls` flavor is in use
# Don't expect use the Darwin flavor ls
# if ls --color > /dev/null 2>&1;
# then # GNU `ls`
#   colorflag="--color"
# else # OS X `ls`
#   colorflag="-G"
# fi
# alias ls="command ls -h ${colorflag}"
# unset -v colorflag
# alias ls="command ls --color=auto"
# Not works
# export LS_OPTS='--color=auto'

# Human Readable
#alias ls="ls --color=auto -h"

# List all files colorized in long format
#alias l="ls -lF"

# List all files colorized in long format, including dot files
#alias la="ls -aF"

#alias ll="ls -alF"

# List only directories
alias lsd='ls -lF | grep "^d"'

# List as tree
listdirtree()
{
    ls -R "$@" | grep ":$" | sed -e 's/:$//' -e 's/[^-][^\/]*\//--/g' -e 's/^/   /' -e 's/-/|/';

}

# }} ls

